### PR TITLE
Completed changes for the Global Exception Handler.

### PR DESCRIPTION
**Pull request by AlejandraBC**

### CODE REVIEW

**Comment by ivanflores15** [comment]
Hi Alejandra. Seems like your change impact on something. could you please check inside of jenkins what is happening and fix what is broken.

**Comment by luisgalindoluna** [comment]
Hey Alejandra hate to do this to you, right after you did another push. But your branch now has conflicts with the changed that just got merged. Take care of it please.

**Review by ivanflores15 — APPROVED** [review]
Awesome job!!!

**Review by EmiliaGuillen-dev — APPROVED** [review]
looks great!

**Pull request merged**
