### PR TITLE
Implementation delete operation to delete a user by id.

### PR DESCRIPTION
**Pull request by Gra2411**
Implementation of the delete method to delete by user ID.

### CODE REVIEW

**Review by luisgalindoluna — CHANGES_REQUESTED** [review]
Looks fine, however another US was merged first so please pull from develop and merge those changes to your branch and of course resolve conflicts.

**Comment by ivanflores15** [comment]
Yes, merge develop latest with your feature local branch to resolve conflicts.

**Review by ivanflores15 — APPROVED** [review]
good job

**Review by luisgalindoluna — APPROVED** [review]
Looks good

**Review by EmiliaGuillen-dev — APPROVED** [review]
looks good

**Pull request merged**
